[package]
name = "serde_unit_struct"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_unit_struct_derive = { path = "../serde_unit_struct_derive" }

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
